name: reverse_default
include:
  - path:
      - compose_extends/network.include.yaml

services:
  reverse:
    extends:
      file: compose_extends/docker-compose.base.yaml
      service: reverse
    volumes:
      - "./locations:/etc/nginx/locations:ro"
      - "./configuration:/etc/nginx/configuration:ro"
      - "./sites-enabled:/etc/nginx/sites-enabled:ro"
      - "./error-pages:/etc/nginx/error-pages:ro"
      - "./resources:/var/www/html/resources:ro"
      - "./ssl:/etc/nginx/ssl:ro"
      - "./logs:/var/log/nginx/"
    ports:
      - 80:80
      - 443:443
    networks:
      - services
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf

configs:
  nginx_config:
    name: times_new_nginx_config
    file: ./nginx_config/nginx.conf
    external: false
