name: reverse_dev
include:
  - path:
      - compose_extends/network.include.yaml

services:
  reverse:
    extends:
      file: compose_extends/docker-compose.base.yaml
      service: reverse
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_devserver
      args:
        CONT_IMG_VER: "v1.0.0"
    pull_policy: missing
    volumes:
      - "./sites-enabled:/etc/nginx/sites-enabled:ro"
    ports:
      - 80:80
      - 443:443
    networks:
      - services
    secrets:
      - source: softsols_cert
        target: /etc/nginx/ssl/live/softsols.ru/fullchain.pem
      - source: softsols_key
        target: /etc/nginx/ssl/live/softsols.ru/privkey.pem

secrets:
  softsols_cert:
    name: softsols_cert
    file: ./ssl/live/softsols.ru/fullchain.pem
    external: false
  softsols_key:
    name: softsols_key
    file: ./ssl/live/softsols.ru/privkey.pem
    external: false